package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* jeudi 30 novembre 2023 09 h 12 WAT
*/


// L'interface IConversionRemote définit les opérations pour la conversion.
public interface IConversionRemoteOperations 
{

  // @return Le montant converti.
  double conversionMontant (double mt);
} // interface IConversionRemoteOperations
